# These are supported funding model platforms

github: shivam785 # Your GitHub username
patreon: # Add your Patreon username if you have one
open_collective: # Add your Open Collective username if you have one
ko_fi: # Add your Ko-fi username if you have one
tidelift: # Add your Tidelift platform-name/package-name
community_bridge: # Add your Community Bridge project name
liberapay: # Add your Liberapay username
issuehunt: # Add your IssueHunt username
otechie: # Add your Otechie username
lfx_crowdfunding: # Add your LFX Crowdfunding project name
custom: [''] # Your custom sponsorship link
